// After `astro build`: write dist/_headers with a Content-Security-Policy whose script-src
// allows exactly the inline scripts the built pages carry (by hash) and nothing from another
// origin; then check the output against BRIEF.md §1 — nothing loaded from another origin, and
// the landing page's JavaScript under 60 KB compressed.
import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir, stat, copyFile, access } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { join, relative, resolve } from 'node:path';

const DIST = resolve(import.meta.dirname, '..', 'dist');
const SITE_HOSTS = new Set(['siriuside.com']);

async function* walk(dir) {
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const p = join(dir, entry.name);
		if (entry.isDirectory()) { yield* walk(p); } else { yield p; }
	}
}

const html = [];
for await (const f of walk(DIST)) { if (f.endsWith('.html')) { html.push(f); } }

// 1. inline scripts → hashes; external references → must be same-origin
const hashes = new Set();
const foreign = [];
const scriptRe = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
const refRe = /<(?:script|link|img|source|video|iframe)\b[^>]*?(?:src|href)=["']([^"']+)["']/gi;
for (const file of html) {
	const text = await readFile(file, 'utf8');
	for (const m of text.matchAll(scriptRe)) {
		const attrs = m[1];
		const body = m[2];
		if (/\bsrc=/.test(attrs)) { continue; }
		if (/type=["']application\/(ld\+json|json)["']/.test(attrs)) { continue; } // data blocks, not executed
		if (!body.trim()) { continue; }
		hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
	}
	for (const m of text.matchAll(refRe)) {
		const url = m[1];
		if (/^(https?:)?\/\//i.test(url)) {
			const host = new URL(url, 'https://siriuside.com').host;
			if (!SITE_HOSTS.has(host)) { foreign.push(`${relative(DIST, file)}: ${url}`); }
		}
	}
}

// Expressive Code names its stylesheet by a hash of its configuration. Pages rendered through the
// content loader's renderMarkdown (the repository documents) get a second configuration, so they
// reference an ec.<hash>.css that was never emitted. The styles are the same; alias the file.
const ecRefs = new Set();
for (const file of html) {
	for (const m of (await readFile(file, 'utf8')).matchAll(/\/_astro\/(ec\.[a-z0-9]+\.css)/g)) { ecRefs.add(m[1]); }
}
const ecFiles = (await readdir(join(DIST, '_astro'))).filter((f) => /^ec\.[a-z0-9]+\.css$/.test(f));
// The same stylesheet is inlined into each page that links it: one render-blocking request fewer
// before the first paint of a docs page with a code block (style-src allows inline styles).
const ecCss = ecFiles.length ? await readFile(join(DIST, '_astro', ecFiles[0]), 'utf8') : '';
if (ecCss) {
	let inlined = 0;
	for (const file of html) {
		const text = await readFile(file, 'utf8');
		const next = text.replace(/<link rel="stylesheet" href="\/_astro\/ec\.[a-z0-9]+\.css">/g, () => { inlined++; return `<style>${ecCss}</style>`; });
		if (next !== text) { await writeFile(file, next); }
	}
	if (inlined) { console.log(`postbuild: inlined Expressive Code's stylesheet into ${inlined} page(s)`); }
}
for (const ref of ecRefs) {
	if (ecFiles.includes(ref)) { continue; }
	if (ecFiles.length === 0) { console.error(`postbuild: ${ref} is referenced but no Expressive Code stylesheet was emitted`); process.exitCode = 1; continue; }
	await copyFile(join(DIST, '_astro', ecFiles[0]), join(DIST, '_astro', ref));
	console.log(`postbuild: aliased ${ecFiles[0]} → ${ref} (Expressive Code's second configuration hash)`);
}

const csp = [
	"default-src 'self'",
	`script-src 'self' 'wasm-unsafe-eval' ${[...hashes].sort().join(' ')}`.trim(),
	"style-src 'self' 'unsafe-inline'",
	"img-src 'self' data:",
	"font-src 'self'",
	"media-src 'self'",
	"connect-src 'self'",
	"manifest-src 'self'",
	"worker-src 'self'",
	"object-src 'none'",
	"base-uri 'self'",
	"form-action 'self'",
	"frame-ancestors 'none'",
	'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/postbuild.mjs — do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/pagefind/*
  Cache-Control: public, max-age=86400

# Pagefind fetches its entry file and loader by fixed names, so a deploy must not be hidden by a stale copy.
/pagefind/pagefind-entry.json
  ! Cache-Control
  Cache-Control: no-cache
/pagefind/pagefind.js
  ! Cache-Control
  Cache-Control: no-cache
/pagefind/pagefind-ui.js
  ! Cache-Control
  Cache-Control: no-cache
/pagefind/pagefind-highlight.js
  ! Cache-Control
  Cache-Control: no-cache

/og/*
  Cache-Control: public, max-age=86400

/rss.xml
  Content-Type: application/rss+xml; charset=utf-8
  Cache-Control: public, max-age=3600

/.well-known/security.txt
  Content-Type: text/plain; charset=utf-8
`;
await writeFile(join(DIST, '_headers'), headers);
console.log(`postbuild: _headers written — ${hashes.size} inline script hash(es), ${html.length} pages scanned`);

// 2. the landing page's JavaScript budget
const index = await readFile(join(DIST, 'index.html'), 'utf8');
let jsBytes = 0; const scripts = []; const seen = new Set();
// Every script the page loads, following static imports, so a chunk pulled in by another chunk counts too.
const queue = [...index.matchAll(/<script\b[^>]*\bsrc=["']([^"']+)["']/g)].map((m) => m[1]);
while (queue.length) {
	const ref = queue.shift();
	if (seen.has(ref)) { continue; }
	seen.add(ref);
	const p = join(DIST, ref);
	try {
		const b = await readFile(p); const gz = gzipSync(b).length; jsBytes += gz; scripts.push(`${ref} ${gz} B gz`);
		for (const im of b.toString('utf8').matchAll(/(?:import|from)\s*["']([^"']+\.js)["']/g)) { queue.push(new URL(im[1], 'https://x' + ref).pathname); }
	} catch { scripts.push(`${ref} (missing)`); }
}
console.log(`postbuild: landing-page JavaScript ${jsBytes} B gzipped across ${scripts.length} file(s)`);
for (const s of scripts) { console.log('  ' + s); }
let failed = false;
if (jsBytes > 60 * 1024) { console.error(`postbuild: landing-page JavaScript ${jsBytes} B exceeds the 60 KB budget`); failed = true; }
if (foreign.length) { console.error('postbuild: resources from another origin:'); for (const f of foreign) { console.error('  ' + f); } failed = true; }
if (failed) { process.exitCode = 1; } else { console.log('postbuild: no third-party resources; budgets hold'); }
