// After `astro build`: write dist/_headers with a Content-Security-Policy whose script-src
// allows exactly the inline scripts the built pages carry (by hash) and nothing from another
// origin; then check the output against BRIEF.md §1 — nothing loaded from another origin, and
// the landing page's JavaScript under 60 KB compressed.
import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { join, relative, resolve } from 'node:path';

const DIST = resolve(import.meta.dirname, '..', 'dist');
const SITE_HOSTS = new Set(['siriuside.com']);

async function* walk(dir) {
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const p = join(dir, entry.name);
		if (entry.isDirectory()) { yield* walk(p); } else { yield p; }
	}
}

const html = [];
for await (const f of walk(DIST)) { if (f.endsWith('.html')) { html.push(f); } }

// 1. inline scripts → hashes; external references → must be same-origin
const hashes = new Set();
const foreign = [];
const scriptRe = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
const refRe = /<(?:script|link|img|source|video|iframe)\b[^>]*?(?:src|href)=["']([^"']+)["']/gi;
for (const file of html) {
	const text = await readFile(file, 'utf8');
	for (const m of text.matchAll(scriptRe)) {
		const attrs = m[1];
		const body = m[2];
		if (/\bsrc=/.test(attrs)) { continue; }
		if (/type=["']application\/(ld\+json|json)["']/.test(attrs)) { continue; } // data blocks, not executed
		if (!body.trim()) { continue; }
		hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
	}
	for (const m of text.matchAll(refRe)) {
		const url = m[1];
		if (/^(https?:)?\/\//i.test(url)) {
			const host = new URL(url, 'https://siriuside.com').host;
			if (!SITE_HOSTS.has(host)) { foreign.push(`${relative(DIST, file)}: ${url}`); }
		}
	}
}

const csp = [
	"default-src 'self'",
	`script-src 'self' 'wasm-unsafe-eval' ${[...hashes].sort().join(' ')}`.trim(),
	"style-src 'self' 'unsafe-inline'",
	"img-src 'self' data:",
	"font-src 'self'",
	"media-src 'self'",
	"connect-src 'self'",
	"manifest-src 'self'",
	"worker-src 'self'",
	"object-src 'none'",
	"base-uri 'self'",
	"form-action 'self'",
	"frame-ancestors 'none'",
	'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/postbuild.mjs — do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/pagefind/*
  Cache-Control: public, max-age=86400

/og/*
  Cache-Control: public, max-age=86400

/rss.xml
  Content-Type: application/rss+xml; charset=utf-8
  Cache-Control: public, max-age=3600

/.well-known/security.txt
  Content-Type: text/plain; charset=utf-8
`;
await writeFile(join(DIST, '_headers'), headers);
console.log(`postbuild: _headers written — ${hashes.size} inline script hash(es), ${html.length} pages scanned`);

// 2. the landing page's JavaScript budget
const index = await readFile(join(DIST, 'index.html'), 'utf8');
let jsBytes = 0; const scripts = [];
for (const m of index.matchAll(/<script\b[^>]*\bsrc=["']([^"']+)["']/g)) {
	const p = join(DIST, m[1]);
	try { const b = await readFile(p); const gz = gzipSync(b).length; jsBytes += gz; scripts.push(`${m[1]} ${gz} B gz`); } catch { scripts.push(`${m[1]} (missing)`); }
}
console.log(`postbuild: landing-page JavaScript ${jsBytes} B gzipped across ${scripts.length} file(s)`);
for (const s of scripts) { console.log('  ' + s); }
let failed = false;
if (jsBytes > 60 * 1024) { console.error(`postbuild: landing-page JavaScript ${jsBytes} B exceeds the 60 KB budget`); failed = true; }
if (foreign.length) { console.error('postbuild: resources from another origin:'); for (const f of foreign) { console.error('  ' + f); } failed = true; }
if (failed) { process.exitCode = 1; } else { console.log('postbuild: no third-party resources; budgets hold'); }
